In [1]:
from utils import *
# from sknn import *
from sknn_sparse_matrix import *
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import norm

In [2]:
FOLDER_TRAIN = 'data/train/'
FOLDER_TEST = 'data/test/'
train, test = load_dataset(FOLDER_TRAIN, FOLDER_TEST, feather=True)

load_dataset
 -- loaded in: 0.23580169677734375s
 -- filtered in: 0.2994804382324219s
 -- actions:  664712
 -- items:  170089
 -- lists:  10000


In [3]:
a = train['actions']['playlist_id'].values
b = train['actions']['track_id'].values
a.shape[0]

664712

In [4]:
OUTPUT_FOLDER = 'output/'
rec = SessionKNN(2000, 0, sampling='else', idf_weight=1, folder=OUTPUT_FOLDER)

In [5]:
rec.train(train, test)

Matrix build time:  0.03988385200500488
IDF calculate time:  0.0029532909393310547


In [6]:
test_data = list(zip(test['playlists']['playlist_id'], test['playlists']['name'], 
                     test['playlists']['num_tracks'], test['playlists']['num_samples']))
pid, name, ntracks, nsamples = test_data[5000]
num_hidden = ntracks - nsamples

In [7]:
tracks = test['actions'][test['actions']['playlist_id']==pid]['track_id'].values
artist_ids = test['actions'][test['actions']['playlist_id']==pid]['artist_id'].values

In [8]:
rec.predict(name, tracks, playlist_id=pid, artists=artist_ids, num_hidden=num_hidden) 

Find neighbor time:  0.008910417556762695
Score items time:  0.004996299743652344


track_id  confidence
0         535    4.948914
1        6579    1.906740
2        3333    1.516862
3       13565    1.460623
4        8929    1.343805
..        ...         ...
495     28937    0.212865
496      7158    0.212836
497       533    0.212671
498     14405    0.212602
499     74129    0.212554

[500 rows x 2 columns]

### Ignore things below

In [18]:
print(tracks)

[   536 130904  53935  92414 101662]


In [13]:
import time
start = time.time()
for i in range(5):
    print(5)
end = time.time()
print(start)
print(end)

5
5
5
5
5
1682004521.935925
1682004521.935925


In [10]:
a = set([1, 3, 4, 6, 8])
b = set([1, 2, 3, 4, 5])
a & b
li = len(a & b)
la = len(a)
lb = len(b)
li / ( sqrt(la) * sqrt(lb) )

0.5999999999999999

In [19]:
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
a = csr_matrix((data, indices, indptr), shape=(3, 3))
# r,c = (a.sum(axis=0)).nonzero()
# c

In [20]:
a.toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [21]:
np.log(a.sum(axis=0))

matrix([[1.60943791, 1.60943791, 2.39789527]])

In [22]:
csr_matrix.multiply(a, np.log(a.sum(axis=0))).toarray()

array([[ 1.60943791,  0.        ,  4.79579055],
       [ 0.        ,  0.        ,  7.19368582],
       [ 6.43775165,  8.04718956, 14.38737164]])

In [6]:
col = np.zeros(2)
row = np.array([0, 1])
data = np.ones(2)
tracks_vector = csr_matrix((data, (row, col)), shape=(3, 1))
tracks_vector.toarray()

array([[1.],
       [1.],
       [0.]])

In [9]:
norm(tracks_vector)

1.4142135623730951

In [21]:
(a.dot(tracks_vector)).multiply(b)

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in COOrdinate format>

In [13]:
b = 1 / norm(a, axis=1)
b

array([0.4472136 , 0.33333333, 0.11396058])

In [22]:
c = np.ones(3)
d = csr_matrix.multiply(a, b)
d.dot(c)

array([1.34164079, 1.        , 1.70940865])

In [24]:
d.toarray()

array([[0.4472136 , 0.        , 0.89442719],
       [0.        , 0.        , 1.        ],
       [0.45584231, 0.56980288, 0.68376346]])

In [66]:
b = np.array([[1], [2], [3]])
csr_matrix.multiply(a, b).toarray()

array([[ 1,  0,  2],
       [ 0,  0,  6],
       [12, 15, 18]])

In [64]:
b

matrix([[ 5,  5, 11]], dtype=int32)

In [11]:
b = np.array([[1, 2, 3]])
a.multiply(b.T)toarray()

array([[ 1,  0,  6],
       [ 0,  0,  9],
       [ 4, 10, 18]])

In [31]:
a.sum(axis=0).nonzero()

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))

In [44]:
np.dot(indices, data)

22

In [45]:
indices.sum()

7

In [35]:
a = np.array([1, 2, 3, 3])
np.unique(a)

array([1, 2, 3])

In [33]:
b = pd.DataFrame()
b['test'] = a.nonzero()
b


test
0  [0, 1, 2]

In [23]:
import numpy as np
from scipy.sparse import csr_matrix

# Create a sparse CSR matrix
data = np.array([1, 2, 3])
indices = np.array([0, 0, 0])
indptr = np.array([0, 1, 2, 3])
sparse_mat = csr_matrix((data, indices, indptr), shape=(3, 1))

# Create a dense numpy array
dense_arr = np.array([2, 3, 4])

# Perform element-wise multiplication
result = sparse_mat.multiply(dense_arr.reshape(-1, 1))

print(result.toarray())

[[ 2]
 [ 6]
 [12]]


In [10]:
a = np.array([1, 0, 0, 3, 0, 4])
t1, _ = a.nonzero()

ValueError: not enough values to unpack (expected 2, got 1)